import OpenAI from 'openai';
import { env } from '../config/env';

export class OpenAIService {
  private client: OpenAI | null = null;

  constructor() {
    if (env.OPENAI_API_KEY) {
      this.client = new OpenAI({
        apiKey: env.OPENAI_API_KEY,
      });
    }
  }

  /**
   * インシデントを分析してアクション提案を生成
   */
  async analyzeIncident(incident: {
    type: string;
    title: string;
    description?: string;
    payloadJson: any;
    source: string;
  }): Promise<{
    hypothesis: string;
    reproductionSteps: string[];
    suggestedActions: Array<{
      type: string;
      description: string;
      priority: 'high' | 'medium' | 'low';
    }>;
    summary: string;
  }> {
    if (!this.client) {
      throw new Error('OpenAI API key not configured');
    }

    const prompt = this.buildAnalysisPrompt(incident);

    const completion = await this.client.chat.completions.create({
      model: env.OPENAI_MODEL,
      messages: [
        {
          role: 'system',
          content: `You are an expert DevOps engineer and SRE. Analyze incidents from CI/CD pipelines and deployment platforms, identify root causes, and suggest actionable remediation steps. Respond in JSON format.`,
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.3,
      response_format: { type: 'json_object' },
    });

    const content = completion.choices[0].message.content;
    if (!content) {
      throw new Error('No response from OpenAI');
    }

    const analysis = JSON.parse(content);

    return {
      hypothesis: analysis.hypothesis || 'Unable to determine root cause',
      reproductionSteps: analysis.reproduction_steps || [],
      suggestedActions: analysis.suggested_actions || [],
      summary: analysis.summary || '',
    };
  }

  /**
   * 分析プロンプトを構築
   */
  private buildAnalysisPrompt(incident: {
    type: string;
    title: string;
    description?: string;
    payloadJson: any;
    source: string;
  }): string {
    return `
Analyze the following DevOps incident and provide a detailed analysis:

**Incident Type:** ${incident.type}
**Source:** ${incident.source}
**Title:** ${incident.title}
**Description:** ${incident.description || 'N/A'}

**Payload:**
\`\`\`json
${JSON.stringify(incident.payloadJson, null, 2)}
\`\`\`

Please provide your analysis in the following JSON format:
{
  "hypothesis": "Your hypothesis about the root cause",
  "reproduction_steps": ["Step 1", "Step 2", ...],
  "suggested_actions": [
    {
      "type": "COMMENT_PR | CREATE_ISSUE | ROLLBACK | etc",
      "description": "Detailed description of the action",
      "priority": "high | medium | low"
    }
  ],
  "summary": "Brief summary of the incident and recommended next steps"
}
    `.trim();
  }

  /**
   * PR/Issueコメント用のメッセージを生成
   */
  async generateCommentMessage(analysis: {
    hypothesis: string;
    reproductionSteps: string[];
    suggestedActions: any[];
    summary: string;
  }): Promise<string> {
    return `
## 🤖 AI-Powered Incident Analysis

${analysis.summary}

### Root Cause Hypothesis
${analysis.hypothesis}

${analysis.reproductionSteps.length > 0 ? `
### Reproduction Steps
${analysis.reproductionSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}
` : ''}

### Suggested Actions
${analysis.suggestedActions.map(action => `- **[${action.priority.toUpperCase()}]** ${action.description}`).join('\n')}

---
*Generated by Agentic DevOps Autopilot*
    `.trim();
  }
}

export const openaiService = new OpenAIService();
